name: Add to Aurora Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  track:
    if: github.repository_owner == 'AuroraEditor'
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/AuroraEditor/projects/1
          github-token: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
          labeled: noproject
          label-operator: NOT
