name: Build & Lint

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build_and_lint:
    runs-on: macos-12
    timeout-minutes: 10 # If a action exceeds 10 mins, it probably isn't ever going to complete.
    steps:
      - uses: actions/checkout@v3

      - name: MacOS Version
        run: sw_vers

      - name: Toolchain version
        run: swift -version

      - name: SwiftLint (version)
        run: swiftlint version

      - name: Check SwiftLint Version
        id: check_swiftlint_version
        run: |
          current_version=$(swiftlint version)
          latest_version=$(brew info swiftlint | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+")
          if [ "$current_version" == "$latest_version" ]; then
            echo "SwiftLint is up to date. Skipping upgrade step."
            echo "::set-output name=upgrade_required::false"
          else
            echo "SwiftLint needs to be upgraded."
            echo "::set-output name=upgrade_required::true"
          fi
        shell: bash

      - name: Upgrade SwiftLint
        run: |
          upgrade_required="${{ steps.check_swiftlint_version.outputs.upgrade_required }}"
          if [ "$upgrade_required" == "true" ]; then
            brew upgrade swiftlint
          fi
        shell: bash

      - name: SwiftLint (GH Actions)
        run: swiftlint --reporter github-actions-logging --strict

      - name: Swift (clean) Build
        run: set -o pipefail && xcodebuild -workspace "Aurora Editor.xcworkspace" -scheme "Aurora Editor" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --renderer github-actions
