name: Run Aurora Editor Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  tests:
    runs-on: macos-13
    timeout-minutes: 10 # If a action exceeds 10 mins, it probably isn't ever going to complete.
    steps:
      - uses: actions/checkout@v3

      - name: MacOS Version
        run: sw_vers

      - name: Toolchain version
        run: swift -version
        
      - name: "Select Xcode (Default)"
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Aurora Editor (Tests)
        run: |
          xcodebuild -workspace "Aurora Editor.xcworkspace" \
          -scheme "Aurora Editor (Tests)" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          test
